version: "3.9"

services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DOCKER_CLIENT_TIMEOUT: 300

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: health
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
